### ISSUE TITLE
How to display trimmerView in a SmalllView.

### ISSUE THREAD

**Issue by ajay2c9** [prynt/PryntTrimmerView#14] opened 2017-10-17 11:39 UTC
I am using this PryntTrimmerView in my project.My project is in Objective-c . i drag and drop the trimmer files in my project. According to the design i have a small view with height of 56 height i already using the AVplayer to play the videos. how to display the trimmerView in the Small View.and add the delegate methods. I tried ... but i am unable to access delegate methods and the properties to change the colour and assign the asset to the trimmerView.I don't understand the sample code. please give suggestions to implement the trimmerView in Objective-c code. or please provide the sample code totally in One ViewController to understand easily.

Thank you

**Comment by HHK1** [comment] 2017-10-17 15:20
I'm closing this issue as this is a duplicate of your other one #15 which is better documented.

**Closed by HHK1** 2017-10-17 15:20 UTC
